#ifndef __CONTROLLER_LOOP_PARAM_H
#define __CONTROLLER_LOOP_PARAM_H

#define STR_POSITION_LOOP_KP 1.0
#define STR_POSITION_LOOP_KI 0.0
#define STR_POSITION_LOOP_KD 0.0
#define STR_POSITION_LOOP_OUTPUT_MAX 200.0
#define STR_POSITION_LOOP_OUTPUT_MIN -200.0
#define STR_POSITION_LOOP_INTEGRAL_MAX 100.0

#define STR_SPEED_LOOP_KP 10
#define STR_SPEED_LOOP_KI 0.0
#define STR_SPEED_LOOP_KD 0.0
#define STR_SPEED_LOOP_OUTPUT_MAX 1000.0
#define STR_SPEED_LOOP_OUTPUT_MIN -1000.0
#define STR_SPEED_LOOP_INTEGRAL_MAX 100.0

#define DRV_SPEED_LOOP_KP 0.0
#define DRV_SPEED_LOOP_KI 0.0
#define DRV_SPEED_LOOP_KD 0.0
#define DRV_SPEED_LOOP_OUTPUT_MAX 0.0
#define DRV_SPEED_LOOP_OUTPUT_MIN 0.0
#define DRV_SPEED_LOOP_INTEGRAL_MAX 100.0

#endif
